version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=trabalholab
      - RABBITMQ_DEFAULT_PASS=I<)D,tF5B8w8
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/data/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/data/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge